@rootUrl = http://localhost:8080
@requestPath = /api/v1/auth

GET {{rootUrl}}{{requestPath}}/login


### Expected 400 Bad Request
POST {{rootUrl}}{{requestPath}}/login
Content-Type: application/json

{
    "Email": "isaac.newton@example.invalid",
    "Password": "pass"
}