name: New Tag Created

on:
  push:
    tags:
      - '**'

jobs:
  build_and_test:
    uses: ./.github/workflows/push.yml

  create_release_draft:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: gh release create "$TAG" --title="$TAG" --draft

  create_and_push_container_images:
    needs: [ create_release_draft ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker QEMU Emulation
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build Api
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dreamer.Api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: amieldelatorre/dreamer-api:${{  github.ref_name }},amieldelatorre/dreamer-api:latest
      
      - name: Docker Build Web Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/web
          file: ./frontend/web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: amieldelatorre/dreamer-web:${{  github.ref_name }},amieldelatorre/dreamer-web:latest

  publish-release:
    needs: [ create_release_draft, create_and_push_container_images ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: gh release edit "$TAG" --draft=false
    